package simx.components.renderer.jvr.ontology

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

package object types{
  def init(){}
	object DiffuseColor extends simx.core.ontology.SVarDescription(simx.core.ontology.types.DiffuseColor as simx.core.ontology.Symbols.diffuseColor withType classOf[de.bht.jvr.util.Color] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/renderer/SimxRenderer.owl#DiffuseColor")
	
	object HeadTransform extends simx.core.ontology.SVarDescription(simx.core.ontology.types.HeadTransform as simx.core.ontology.Symbols.headTransform withType classOf[de.bht.jvr.core.Transform] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/renderer/SimxRenderer.owl#HeadTransform")
	
	object PostProcessingEffect extends simx.core.ontology.SVarDescription(simx.core.ontology.types.NullType as simx.core.ontology.Symbols.postProcessingEffect withType classOf[simx.components.renderer.jvr.PostProcessingEffect] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/renderer/JVR/JVR.owl#PostProcessingEffect")
	
	object Scale extends simx.core.ontology.SVarDescription(simx.core.ontology.types.Scale as simx.core.ontology.Symbols.scale withType classOf[de.bht.jvr.core.Transform] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/concepts/BasicTypes.owl#Scale")
	object ShaderEffect extends simx.core.ontology.SVarDescription(simx.core.ontology.types.NullType as simx.core.ontology.Symbols.shaderEffect withType classOf[simx.components.renderer.jvr.ShaderEffect] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/renderer/JVR/JVR.owl#ShaderEffect")
	object SpecularColor extends simx.core.ontology.SVarDescription(simx.core.ontology.types.SpecularColor as simx.core.ontology.Symbols.specularColor withType classOf[de.bht.jvr.util.Color] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/renderer/SimxRenderer.owl#SpecularColor")
	
	object Transformation extends simx.core.ontology.SVarDescription(simx.core.ontology.types.Transformation as simx.core.ontology.Symbols.transformation withType classOf[de.bht.jvr.core.Transform] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/SimxCoreOntology.owl#Transformation")
	
	object ViewPlatform extends simx.core.ontology.SVarDescription(simx.core.ontology.types.ViewPlatform as simx.core.ontology.Symbols.viewPlatform withType classOf[de.bht.jvr.core.Transform] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/renderer/SimxRenderer.owl#ViewPlatform")
}