package simx.components.renderer.jvr.ontology.functions

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

import simx.components.renderer.jvr.ontology.types._
import simx.core.ontology.types._

trait Functions{

}